language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - git checkout gh-pages
  - git merge doc
  - cd ./mark
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - node index.js
  
  
after_script: 
  - cd ..
  - git config user.name "vczero"
  - git config user.email "wlhmyit@126.com" 
  - git add .
  - git commit -m "update website"
  - git push origin gh-pages

# E: Build LifeCycle

branches:
  only:
    - doc 
    - gh-pages
env:
 global:
   - GH_REF: github.com/vczero/dockit.git 
  

